# -*- coding: utf-8 -*-
"""Ariima_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nCH2Si4oeePa5aAMX48hkngsQRmRtEq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA

def load_model(path):
    df = pd.read_csv(path)

    df['posted_date'] = pd.to_datetime(df['posted_date'])
    skills = df['skills_required'].unique()
    months = pd.date_range(start='2024-01-01', end='2026-04-01', freq='MS')

    #trend yang dikumpulin berdasarkan berbagai source di internet, dan ini yang didapat
    trend_map = {
        'pytorch': 'NAIK', 'tensorflow': 'STABIL', 'aws': 'TURUN', 'c++': 'STABIL',
        'gcp': 'STABIL', 'cuda': 'NAIK', 'r': 'STABIL', 'hugging face': 'NAIK',
        'flask': 'NAIK', 'scikit-learn': 'STABIL', 'fastapi': 'NAIK', 'pandas': 'STABIL',
        'azure': 'STABIL', 'numpy': 'STABIL', 'excel': 'STABIL', 'keras': 'STABIL',
        'python': 'NAIK', 'power bi': 'NAIK', 'mlflow': 'NAIK', 'langchain': 'NAIK',
        'reinforcement learning': 'NAIK', 'sql': 'STABIL', 'angular': 'TURUN',
        'javascript': 'STABIL', 'jquery': 'STABIL', 'react': 'NAIK',
        'typescript': 'NAIK', 'postgresql': 'STABIL', 'html': 'STABIL',
        'css': 'STABIL', 'webpack': 'STABIL', 'go': 'NAIK', 'java': 'STABIL',
        'vue': 'NAIK', 'kubernetes': 'NAIK', 'node.js': 'NAIK', 'tableau': 'STABIL',
        'spring boot': 'NAIK', 'php': 'STABIL', 'graphql': 'NAIK'
    }

    new_data = []
    np.random.seed(42)

    for skill in skills:
        trend_direction = trend_map.get(skill, 'stable')
        target = np.random.randint(5, 12)
        current_value = target

        for i, month in enumerate(months):
            if trend_direction == 'NAIK':
                drift = 0.1
            elif trend_direction == 'TURUN':
                drift = -0.1
            else:
                drift = 0

            reversion = -0.05 * (current_value - target)
            noise = np.random.normal(0, 0.1)
            current_value = current_value + drift + reversion + noise
            current_value = max(0, current_value)
            count = np.random.poisson(lam=max(0.1, current_value))

            for _ in range(count):
                new_data.append({
                    "posted_date": month + pd.Timedelta(days=np.random.randint(0, 28)),
                    "skills_required": skill
                })

    df = pd.DataFrame(new_data)

    df['month'] = df['posted_date'].dt.to_period('M').astype(str)

    ts = df.groupby(['month', 'skills_required']).size().reset_index(name='count')
    ts['month'] = pd.to_datetime(ts['month'])

    return ts, trend_map

def run_model(ts, skill, trend_map):

    data = ts[ts['skills_required'] == skill].copy()
    data = data.set_index('month').sort_index()

    full_index = pd.date_range(start=data.index.min(), end=data.index.max(), freq='MS')
    data = data.reindex(full_index)

    data['count'] = data['count'].fillna(0)
    data['smooth'] = data['count'].ewm(span=6).mean()
    series = data['count']

    model = ARIMA(series, order=(1,1,1))
    model_fit = model.fit()

    forecast = model_fit.forecast(steps=3)

    forecast_index = pd.date_range(
        series.index[-1] + pd.DateOffset(months=1),
        periods=len(forecast),
        freq='MS'
    )

    combined = np.append(series.values, forecast.values)
    x = np.arange(len(combined))
    slope = np.polyfit(x, combined, 1)[0]

    if slope > 0.05:
        trend = "NAIK "
    elif slope < -0.05:
        trend = "TURUN "
    else:
        trend = "STABIL "

    print(f"Hasil Analisis untuk Demand '{skill}': {trend}")
    print(f"Slope: {slope:.4f}")
    print(f"Hasil Analisis Untuk Trend {skill} :", trend_map.get(skill))

    return data, forecast, forecast_index, trend, slope

